//
//  Context.h
//  surfingscene
//
//  Created by songhang he on 12-3-22.
//  Copyright (c) 2012年 __MyCompanyName__. All rights reserved.
//
#define MSG_ERROR_URL @"远程服务器无法连接，请确定您的网络是否正常"
#define MSG_ERROR_SERVER @"远程服务器交互失败，请稍候重试"

#define ERROR_MYTYPE @"ERROR_MYTYPE"
#define ERROR_MESSAGE @"errorCode"

#define CLIENTVERSION @"1"

#define CLOUDTYPE_MEETING 1 //会议云
#define CLOUDTYPE_TREVAL 2  //旅游云

#define CLINEPUSHTYPE_FILE 1  //文件
#define CLINEPUSHTYPE_BULLETION 2  //公告
#define CLINEPUSHTYPE_COMMENT 3 //你云我去被评论
#define CLINEPUSHTYPE_PRIVATEMESSAGE 4 //收到私信

#define VERSION_HYY @"IPHONE_HYY" //会议云
#define VERSION_LYY @"IPHONE_LYY" //旅游云

#define VERSION_FJTC_HYY @"FJTC_IPHONE_HYY" //会议云

#define URLFILENAME @"Server"

#define SERVER_URL @"SERVER_URL"
#define URL_USER_ADD @"URL_USER_ADD"
#define URL_USER_PWD @"URL_USER_PWD"
#define URL_USER_LOGIN @"URL_USER_LOGIN"
#define URL_CONFERENCES_LOGINGET @"URL_CONFERENCES_LOGINGET"
#define URL_CONFERENCES_GET @"URL_CONFERENCES_GET"
#define URL_MODULE_GET @"URL_MODULE_GET"
#define URL_AGENDAS_GET @"URL_AGENDAS_GET"
#define URL_AGENDAINFOS_GET @"URL_AGENDAINFOS_GET"
#define URL_TALKMESSAGES_ADD @"URL_TALKMESSAGES_ADD"
#define URL_TALKMESSAGES_GET @"URL_TALKMESSAGES_GET"
#define URL_TALKMESSAGE_GET @"URL_TALKMESSAGE_GET"
#define URL_TALKMESSAGE_DEL @"URL_TALKMESSAGE_DEL"
#define URL_TALKMESSAGE_EDIT @"URL_TALKMESSAGE_EDIT"
#define URL_TALKCOMMENT_ADD @"URL_TALKCOMMENT_ADD"
#define URL_TALKCOMMENTS_GET @"URL_TALKCOMMENTS_GET"
#define URL_TALKCOMMENT_DEL @"URL_TALKCOMMENT_DEL"
#define URL_DINNERPLANS_GET @"URL_DINNERPLANS_GET"
#define URL_DINNERPLANSINFOS_GET @"URL_DINNERPLANSINFOS_GET"
#define URL_DINNERTABLES_GET @"URL_DINNERTABLES_GET"
#define URL_USERINFOS_GET @"URL_USERINFOS_GET"
#define URL_PRIVATEMESSAGE_GETRECEIVE @"URL_PRIVATEMESSAGE_GETRECEIVE"
#define URL_PRIVATEMESSAGE_GETSEND @"URL_PRIVATEMESSAGE_GETSEND"
#define URL_PRIVATEMESSAGE_ADD @"URL_PRIVATEMESSAGE_ADD"
#define URL_PRIVATEMESSAGE_DEL @"URL_PRIVATEMESSAGE_DEL"
#define URL_CLIENTPUSHS_GET @"URL_CLIENTPUSHS_GET"
#define URL_CONFERENCEFILES_GET @"URL_CONFERENCEFILES_GET"
#define URL_RECOMMEND_ADD @"URL_RECOMMEND_ADD"
#define URL_UISTYLES_GET @"URL_UISTYLES_GET"
#define URL_USER_CHECK @"URL_USER_CHECK"
#define URL_EMAIL_SEND @"URL_EMAIL_SEND"
#define URL_VERSION_GET @"URL_VERSION_GET"
#define URL_TALKGROUP_GET @"URL_TALKGROUP_GET"

#define URL_CHECKCODE @"URL_CHECKCODE"
#define URL_LOADCODE @"URL_LOADCODE"
